Settings:

  Ping_List:
    - https://google.com
    - https://facebook.com
    - https://github.com

  Default_Value:
    Timeout: 5

  Version_Control:
    Compare: https://raw.githubusercontent.com/RedFurrFox/Simple_Ping/main/.resources/.version
    Version: v1.0